name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: node-${{ matrix.node }}
    strategy:
      matrix:
        node: [16, 20]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --pure-lockfile --prefer-offline

      - name: Validate
        run: yarn ci

      - name: Build
        run: yarn build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs/examples/bookmarks'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
